import { type NextPage } from "next"
import Head from "next/head"

import { AuthPage } from "../components/AuthPage"

// TODO: consider adding Tailwind CSS
const Home: NextPage = () => (
  <>
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <AuthPage />
    </main>
  </>
)

export default Home
